### ISSUE TITLE
Can't get graphql-import-loader work in my Prisma GraphQLServer written in typescript

### ISSUE THREAD

**Issue by zadigus** [graphcool/graphql-import-loader#11]
Hi,
I have been struggling in the last days trying to make this work without any success. What I want to do is configure my graphql server with Webpack 4. The server is written with Typescript. In the end, I want to be able to call something like this in my index.ts file:

```
import { GraphQLServer } from 'graphql-yoga';
import { Prisma } from './generated/prisma';

import resolvers from './resolvers';
import typeDefs from './schema.graphql';

const server = new GraphQLServer({
  typeDefs,
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      endpoint: process.env.PRISMA_ENDPOINT,
      secret: process.env.PRISMA_SECRET, 
      debug: true
    })
  })
});

server.options.port = Number(process.env.PORT) || 4000;
server.options.endpoint = '/';

server.start(() =>
  console.log(`Server is running on http://localhost:${server.options.port}`)
);
```

Critical point here is 

    import typeDefs from './schema.graphql';

Until several days of googling, I wasn't able to find a solution to make this work. 

Here's my package.json:

```
{
  "name": "MyServer",
  "version": "0.0.0",
  "scripts": {
    "start": "dotenv -- nodemon -e ts,graphql -x ts-node src/index.ts",
    "dev": "npm-run-all --parallel start playground",
    "debug": "dotenv -- nodemon -e ts,graphql -x ts-node --inspect src/index.ts",
    "clean": "rimraf dist",
    "tsc": "tsc",
    "playground": "graphql playground",
    "build": "npm run clean && webpack --config ./webpack.prod.js",
    "postinstall": "cross-var prisma login --key $PRISMA_SERVICE_TOKEN && prisma deploy"
  },
  "dependencies": {
    "bcryptjs": "2.4.3",
    "graphql-yoga": "1.7.0",
    "jsonwebtoken": "8.2.0",
    "prisma-binding": "1.5.16"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.1",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "cross-var": "^1.1.0",
    "dotenv-cli": "1.4.0",
    "graphql-cli": "2.15.8",
    "graphql-import-loader": "^0.2.1",
    "json-loader": "^0.5.7",
    "nodemon": "1.17.2",
    "npm-run-all": "4.1.2",
    "prisma": "1.5.1",
    "rimraf": "2.6.2",
    "ts-loader": "^4.2.0",
    "typescript": "2.8.1",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.15",
    "webpack-node-externals": "^1.7.2"
  }
}
```
Here's my webpack config:

```
const webpack = require('webpack');
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
	target: 'node',
	entry: './src/index.ts',
	externals: [nodeExternals()],
	output: {
		filename: '[name].[chunkhash].js',
		chunkFilename: '[name].[chunkhash].js',
		path: path.resolve(__dirname, 'dist'),
		libraryTarget: 'commonjs'
	},
	resolve: {
		extensions: ['.graphql', '.ts', '.js', '.json']
  },
  node: {
    fs: 'empty'
  },
	module: {
		rules: [
			{
                            exclude: /node_modules/,
                            test: /\.ts$/,
                            use: [
				{ loader: 'babel-loader' },
				{ loader: 'ts-loader' },
                            ],
			},
			{
			  test: /\.json$/,
			  exclude: /node_modules/,
			  loader: 'json-loader'
			}, 
			{
				test: /\.graphql$/,
				exclude: /node_modules/,
				loader: 'graphql-import-loader',
			}
		]
	},

	mode: 'development',
};
```
Here's my tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "moduleResolution": "node",
    "module": "commonjs",
    "allowJs": true,
    "sourceMap": true,
    "outDir": "dist",
    "lib": [
      "esnext", "dom"
    ] 
  }, 
  "files": ["typings/typings.d.ts"]
}
```
In addition to my index.ts file, I have defined the following typings.d.ts:

```
declare module '*.json' {
  const content: any
  export default content
}

declare module '*.graphql' {
  const content: any
  export default content
}
```
In that file, I also tried this:

```
declare module '*.graphql' {
  import { DocumentNode } from 'graphql'
  const content: DocumentNode
  export default content
}
```
That doesn't work better. My graphql schemes look like this:
```
# import Post from "./src/generated/database.graphql"

type Query {
  feed: [Post!]!
  drafts: [Post!]!
  post(id: ID!): Post
  me: User
}

type Mutation {
  signup(email: String!, password: String!, name: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  createDraft(title: String!, text: String!): Post!
  publish(id: ID!): Post!
  deletePost(id: ID!): Post!
}

type AuthPayload {
  token: String!
  user: User!
}

type User {
  id: ID!
  email: String!
  name: String!
  posts: [Post!]!
}
```
where "./src/generated/database.graphql" is found at the correct location and is valid (is generated by Prisma deploy). 

My file structure is as follows:

+ database
  + datamodel.graphql
   + ...
+ node_modules
+ src
  + generated
    + database.graphql
    + prisma.ts
  + resolvers
    + Query.ts
    + ...
  + index.ts
  + schema.graphql
  + ...
+ typings
  + typings.d.ts

Now, when I try the following code in my index.ts, I get the "undefined" output:
```
import typeDefs from './schema.graphql';
console.log("schema = " + typeDefs);
```
The output of this console log is:

    schema = undefined

I tried to use 

```import * from typeDefs from './schema.graphql';```

This is outputting the complete schema.graphql file in my console, but then I don't know how to use it in the GraphQLServer. 

Could someone please explain to me how to make this work?

**Comment by zadigus** [comment]
Until now, I was actually able to get that working but somehow not very elegantly. I can do the following:

1. webpack copies the graphql files from the src to the dist folder
2. I use the graphql-import package like this:

```
import { importSchema } from 'graphql-import'

const typeDefs = importSchema('./schema.graphql');

const server = new GraphQLServer({
  typeDefs,
  resolvers,
  ...
});
```
Then, it works. But in this case, I need to be very careful about the location of the graphql files and how I run my server. I really need to 

    cd dist
    node main.mychunk.js

and then it works. If I was able to do what graphql-import-loader promises I can do in its documentation, then I would just need to import the graphql schema and it will be integrated to my final js file in my dist folder. I would not need to let webpack copy the graphql file into the dist folder and I would not need to care how I run my server.

**Comment by zadigus** [comment]
I have posted a similar question here: https://github.com/graphql-boilerplates/typescript-graphql-server/issues/194
Indeed, my code comes from that repo.

**Comment by yamafaktory** [comment]
Please give a try to the following in your typings.d.ts:

```js
declare module '*.graphql' {
  const value: any
  export = value
}
```

Then hopefully importing it like that `import * from typeDefs from './schema.graphql'` should be working...

**Comment by zadigus** [comment]
This is working now. Thank you very much. May I ask you what the difference is between 
```
declare module '*.graphql' {
  const value: any
  export = value
}
```
and
```
declare module '*.graphql' {
  const value: any
  export default value
}
```
?
