### ISSUE TITLE
Error when importing Prisma-generated schema

### ISSUE THREAD

**Issue by lrholmes** [graphcool/graphql-import-loader#5]
I'm getting the following error when importing the Prisma generated file (to use as Prisma `typeDefs` value):

```
ERROR in ./src/generated/database.graphql
Module parse failed: Unexpected token (3492:5)
You may need an appropriate loader to handle this file type.
| 
| """
| The `Long` scalar type represents non-fractional signed whole numeric values.
| Long can represent values between -(2^63) and 2^63 - 1.
| """
```

I can load the file using `graphql-tag/loader`, but then I run into an error with Prisma (`'TypeError: typeDefs.endsWith is not a function'`. What can I do to import the prisma-generated schema file with webpack and use as prisma `typeDefs`?

**Comment by lrholmes** [comment]
Update - I have found that removing the backticks fixes the issue, so maybe the issue is with Prisma itself using bad characters when generating schema (why does this file even need such detailed comments anyway?).

**Comment by akoenig** [comment]
@lrholmes Could you check if the problem exists when you upgrade your `graphql-cli` to the latest version? This has been fixed in https://github.com/graphql-binding/graphql-static-binding/releases/tag/v0.8.1. The backtick shouldn't be in the generated schema anymore then.

Reference: https://github.com/graphcool/prisma/issues/1992

**Comment by lrholmes** [comment]
Looking at your reference that probably was the issue. I have starting using the generated prisma.js file instead of this anyway.

Thanks for your response!

**Comment by jgeschwendt** [comment]
This is also fixed by - https://github.com/graphcool/graphql-import-loader/pull/6
